export const defaultTheme = {
  // Toolbar styles
  toolbar: 'lexkit-toolbar',

  // Editor content styles
  editor: 'lexkit-editor',
  contentEditable: 'lexkit-content-editable',

  // Node styles for Lexical
  paragraph: 'lexkit-paragraph',
  heading: {
    h1: 'lexkit-heading-h1',
    h2: 'lexkit-heading-h2',
    h3: 'lexkit-heading-h3',
    h4: 'lexkit-heading-h4',
    h5: 'lexkit-heading-h5',
    h6: 'lexkit-heading-h6',
  },
  list: {
    ul: 'lexkit-list-ul',
    ol: 'lexkit-list-ol',
    li: 'lexkit-list-li',
  },
  quote: 'lexkit-quote',
  code: 'lexkit-code',
  codeHighlight: {
    atrule: 'lexkit-code-atrule',
    attr: 'lexkit-code-attr',
    boolean: 'lexkit-code-boolean',
    builtin: 'lexkit-code-builtin',
    cdata: 'lexkit-code-cdata',
    char: 'lexkit-code-char',
    class: 'lexkit-code-class',
    'class-name': 'lexkit-code-class-name',
    comment: 'lexkit-code-comment',
    constant: 'lexkit-code-constant',
    deleted: 'lexkit-code-deleted',
    doctype: 'lexkit-code-doctype',
    entity: 'lexkit-code-entity',
    function: 'lexkit-code-function',
    important: 'lexkit-code-important',
    inserted: 'lexkit-code-inserted',
    keyword: 'lexkit-code-keyword',
    namespace: 'lexkit-code-namespace',
    number: 'lexkit-code-number',
    operator: 'lexkit-code-operator',
    prolog: 'lexkit-code-prolog',
    property: 'lexkit-code-property',
    punctuation: 'lexkit-code-punctuation',
    regex: 'lexkit-code-regex',
    selector: 'lexkit-code-selector',
    string: 'lexkit-code-string',
    symbol: 'lexkit-code-symbol',
    tag: 'lexkit-code-tag',
    url: 'lexkit-code-url',
    variable: 'lexkit-code-variable',
  },
  link: 'lexkit-link',
  text: {
    bold: 'lexkit-text-bold',
    italic: 'lexkit-text-italic',
    underline: 'lexkit-text-underline',
    strikethrough: 'lexkit-text-strikethrough',
    code: 'lexkit-text-code',
  },
  image: 'lexical-image',
};
