export const defaultTheme = {
  // Toolbar styles
  toolbar: 'editor-toolbar',

  // Editor content styles
  editor: 'editor-content',
  contentEditable: 'editor-content-editable',

  // Node styles for Lexical
  paragraph: 'editor-paragraph',
  heading: {
    h1: 'editor-heading-h1',
    h2: 'editor-heading-h2',
    h3: 'editor-heading-h3',
    h4: 'editor-heading-h4',
    h5: 'editor-heading-h5',
    h6: 'editor-heading-h6',
  },
  list: {
    ul: 'editor-list-ul',
    ol: 'editor-list-ol',
    li: 'editor-list-li',
  },
  quote: 'editor-quote',
  code: 'editor-code',
  codeHighlight: {
    atrule: 'editor-code-atrule',
    attr: 'editor-code-attr',
    boolean: 'editor-code-boolean',
    builtin: 'editor-code-builtin',
    cdata: 'editor-code-cdata',
    char: 'editor-code-char',
    class: 'editor-code-class',
    'class-name': 'editor-code-class-name',
    comment: 'editor-code-comment',
    constant: 'editor-code-constant',
    deleted: 'editor-code-deleted',
    doctype: 'editor-code-doctype',
    entity: 'editor-code-entity',
    function: 'editor-code-function',
    important: 'editor-code-important',
    inserted: 'editor-code-inserted',
    keyword: 'editor-code-keyword',
    namespace: 'editor-code-namespace',
    number: 'editor-code-number',
    operator: 'editor-code-operator',
    prolog: 'editor-code-prolog',
    property: 'editor-code-property',
    punctuation: 'editor-code-punctuation',
    regex: 'editor-code-regex',
    selector: 'editor-code-selector',
    string: 'editor-code-string',
    symbol: 'editor-code-symbol',
    tag: 'editor-code-tag',
    url: 'editor-code-url',
    variable: 'editor-code-variable',
  },
  link: 'editor-link',
  text: {
    bold: 'editor-text-bold',
    italic: 'editor-text-italic',
    underline: 'editor-text-underline',
    strikethrough: 'editor-text-strikethrough',
    code: 'editor-text-code',
  },
};
